files: "^(riker-macros/.*|config/.*|src/.*|tests/.*|examples/.*|[^/]*)$"
repos:
  - repo: local
    hooks:
      - id: touch_main.rs
        name: touch to enforce cargo clippy https://github.com/rust-lang/rust-clippy/issues/1495 .
        language: system
        entry: sh -c 'touch src/lib.rs'
  - repo: https://github.com/doublify/pre-commit-rust
    rev: 14b3e118cfc36fb87d8d9cbd1305a2238fd85868
    hooks:
      - id: clippy
        name: cargo clippy https://github.com/rust-lang/rust-clippy/blob/master/README.md .
      - id: cargo-check
        name: cargo check https://doc.rust-lang.org/cargo/commands/cargo-check.html .
      - id: fmt
        name: rustfmt https://github.com/rust-lang/rustfmt/blob/master/README.md .
  - repo: https://github.com/prettier/prettier.git
    rev: 2.1.1
    hooks:
      - id: prettier
        name: prettier https://prettier.io/docs/en/ .
