files: "^(riker-macros/.*|config/.*|src/.*|tests/.*|examples/.*|[^/]*)$"
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        name: cargo clippy https://github.com/rust-lang/rust-clippy/blob/master/README.md .
      - id: cargo-check
        name: cargo check https://doc.rust-lang.org/cargo/commands/cargo-check.html .
      - id: fmt
        name: rustfmt https://github.com/rust-lang/rustfmt/blob/master/README.md .
  - repo: https://github.com/pre-commit/mirrors-prettier.git
    rev: v2.2.0
    hooks:
      - id: prettier
        name: prettier https://prettier.io/docs/en/ .
